extends:
  - "@commitlint/config-conventional"
rules:
  header-max-length: [2, always, 72]
  subject-case: [2, never, [start-case, pascal-case, upper-case]]
  body-max-line-length: [2, always, 100]
  footer-max-line-length: [2, always, 100]
