# SPDX-License-Identifier: AGPL-3.0-only
"""Write the Source tables in docs/CATALOG.md from src/threatcull/catalog.yaml.

uv run python scripts/catalog_docs.py          # rewrite the tables
uv run python scripts/catalog_docs.py --check  # exit 1 if they are out of date
"""

from __future__ import annotations

import sys
from pathlib import Path

from threatcull.catalog import CatalogEntry, feed_label, shipped_catalog
from threatcull.web.dashboard import CATEGORY_LABELS

DOC = Path(__file__).resolve().parent.parent / "docs" / "CATALOG.md"
START = "<!-- catalog:start (generated by scripts/catalog_docs.py; do not edit) -->"
END = "<!-- catalog:end -->"
GROUPS = (
    ("IP blocklists", "blocklist", "ip", ""),
    ("Domain blocklists", "blocklist", "domain", ""),
    (
        "Allowlists",
        "allowlist",
        None,
        "Every value on an enabled allowlist is kept out of all Outputs.",
    ),
)


def _row(entry: CatalogEntry) -> str:
    feed = feed_label(entry.url)
    cells = [
        f"**{entry.name}**<br>`{entry.id}`",
        CATEGORY_LABELS.get(entry.category, entry.category),
        f"[{feed}]({entry.url})",
        "yes" if entry.default_enabled else "",
    ]
    return "| " + " | ".join(cell.replace("|", "\\|") for cell in cells) + " |"


def render() -> str:
    catalog = shipped_catalog()
    lines = [
        START,
        "<!-- vale off -->",
        "",
        f"Catalog revision **{catalog.revision}**, {len(catalog.entries)} Sources. "
        f"Needs ThreatCull {catalog.requires or 'any version'} or newer.",
    ]
    for title, role, kind, note in GROUPS:
        entries = [e for e in catalog.entries if e.role == role and kind in (None, e.kind)]
        lines += ["", f"### {title} ({len(entries)})", ""]
        if note:
            lines += [note, ""]
        lines += [
            "| Source | Category | Feed | On by default |",
            "|---|---|---|---|",
            *(_row(entry) for entry in sorted(entries, key=lambda e: e.name.lower())),
        ]
    lines += ["", "<!-- vale on -->", END]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    text = DOC.read_text(encoding="utf-8")
    head, _, rest = text.partition(START)
    _, _, tail = rest.partition(END)
    if not rest or END not in rest:
        print(f"{DOC}: missing the catalog:start / catalog:end markers", file=sys.stderr)
        return 1
    updated = head + render() + tail
    if "--check" in argv:
        if updated != text:
            print(
                "docs/CATALOG.md is out of date: run `make catalog-docs` and commit it",
                file=sys.stderr,
            )
            return 1
        return 0
    DOC.write_text(updated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
